package pl.mbos.bachelor_thesis.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 
/**
 * Entity mapped to table POWER_EEG.
 */
public class PowerEEG {

    private long userId;
    private int lowAlpha;
    private int highAlpha;
    private int lowBeta;
    private int highBeta;
    private int lowGamma;
    private int midGamma;
    private int theta;
    private int delta;
    /** Not-null value. */
    private java.util.Date collectionDate;

    public PowerEEG() {
    }

    public PowerEEG(long userId, int lowAlpha, int highAlpha, int lowBeta, int highBeta, int lowGamma, int midGamma, int theta, int delta, java.util.Date collectionDate) {
        this.userId = userId;
        this.lowAlpha = lowAlpha;
        this.highAlpha = highAlpha;
        this.lowBeta = lowBeta;
        this.highBeta = highBeta;
        this.lowGamma = lowGamma;
        this.midGamma = midGamma;
        this.theta = theta;
        this.delta = delta;
        this.collectionDate = collectionDate;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getLowAlpha() {
        return lowAlpha;
    }

    public void setLowAlpha(int lowAlpha) {
        this.lowAlpha = lowAlpha;
    }

    public int getHighAlpha() {
        return highAlpha;
    }

    public void setHighAlpha(int highAlpha) {
        this.highAlpha = highAlpha;
    }

    public int getLowBeta() {
        return lowBeta;
    }

    public void setLowBeta(int lowBeta) {
        this.lowBeta = lowBeta;
    }

    public int getHighBeta() {
        return highBeta;
    }

    public void setHighBeta(int highBeta) {
        this.highBeta = highBeta;
    }

    public int getLowGamma() {
        return lowGamma;
    }

    public void setLowGamma(int lowGamma) {
        this.lowGamma = lowGamma;
    }

    public int getMidGamma() {
        return midGamma;
    }

    public void setMidGamma(int midGamma) {
        this.midGamma = midGamma;
    }

    public int getTheta() {
        return theta;
    }

    public void setTheta(int theta) {
        this.theta = theta;
    }

    public int getDelta() {
        return delta;
    }

    public void setDelta(int delta) {
        this.delta = delta;
    }

    /** Not-null value. */
    public java.util.Date getCollectionDate() {
        return collectionDate;
    }

    /** Not-null value; ensure this value is available before it is saved to the database. */
    public void setCollectionDate(java.util.Date collectionDate) {
        this.collectionDate = collectionDate;
    }

}
