package pl.mbos.bachelor_thesis.dao;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import android.os.Parcel;
import android.os.Parcelable;

import java.util.Date;
import java.util.List;

/**
 * Entity mapped to table POWER_EEG.
 */
public class PowerEEG implements Parcelable {

    private long userId;
    private int lowAlpha;
    private int highAlpha;
    private int lowBeta;
    private int highBeta;
    private int lowGamma;
    private int midGamma;
    private int theta;
    private int delta;
    /**
     * Not-null value.
     */
    private java.util.Date collectionDate;

    public PowerEEG() {
    }

    public PowerEEG(long userId, int lowAlpha, int highAlpha, int lowBeta, int highBeta, int lowGamma, int midGamma, int theta, int delta, java.util.Date collectionDate) {
        this.userId = userId;
        this.lowAlpha = lowAlpha;
        this.highAlpha = highAlpha;
        this.lowBeta = lowBeta;
        this.highBeta = highBeta;
        this.lowGamma = lowGamma;
        this.midGamma = midGamma;
        this.theta = theta;
        this.delta = delta;
        this.collectionDate = collectionDate;
    }

    public long getUserId() {
        return userId;
    }

    public void setUserId(long userId) {
        this.userId = userId;
    }

    public int getLowAlpha() {
        return lowAlpha;
    }

    public void setLowAlpha(int lowAlpha) {
        this.lowAlpha = lowAlpha;
    }

    public int getHighAlpha() {
        return highAlpha;
    }

    public void setHighAlpha(int highAlpha) {
        this.highAlpha = highAlpha;
    }

    public int getLowBeta() {
        return lowBeta;
    }

    public void setLowBeta(int lowBeta) {
        this.lowBeta = lowBeta;
    }

    public int getHighBeta() {
        return highBeta;
    }

    public void setHighBeta(int highBeta) {
        this.highBeta = highBeta;
    }

    public int getLowGamma() {
        return lowGamma;
    }

    public void setLowGamma(int lowGamma) {
        this.lowGamma = lowGamma;
    }

    public int getMidGamma() {
        return midGamma;
    }

    public void setMidGamma(int midGamma) {
        this.midGamma = midGamma;
    }

    public int getTheta() {
        return theta;
    }

    public void setTheta(int theta) {
        this.theta = theta;
    }

    public int getDelta() {
        return delta;
    }

    public void setDelta(int delta) {
        this.delta = delta;
    }

    /**
     * Not-null value.
     */
    public java.util.Date getCollectionDate() {
        return collectionDate;
    }

    /**
     * Not-null value; ensure this value is available before it is saved to the database.
     */
    public void setCollectionDate(java.util.Date collectionDate) {
        this.collectionDate = collectionDate;
    }

    // KEEP FIELDS - put your custom fields here
    public static Parcelable.Creator<PowerEEG> CREATOR = new Parcelable.Creator<PowerEEG>() {
        @Override
        public PowerEEG createFromParcel(Parcel parcel) {
            return new PowerEEG(parcel.readLong(), parcel.readInt(), parcel.readInt(), parcel.readInt(), parcel.readInt(), parcel.readInt(), parcel.readInt(), parcel.readInt(), parcel.readInt(), new Date(parcel.readLong()));
        }

        @Override
        public PowerEEG[] newArray(int i) {
            return new PowerEEG[i];
        }
    };
    // KEEP FIELDS END

    // KEEP METHODS - put your custom methods here
    @Override
    public int describeContents() {
        return 0;
    }

    @Override
    public void writeToParcel(Parcel parcel, int i) {
        parcel.writeLong(userId);
        parcel.writeInt(lowAlpha);
        parcel.writeInt(highAlpha);
        parcel.writeInt(lowBeta);
        parcel.writeInt(highBeta);
        parcel.writeInt(lowGamma);
        parcel.writeInt(midGamma);
        parcel.writeInt(theta);
        parcel.writeInt(delta);
        parcel.writeLong(collectionDate.getTime());
    }

    public PowerEEG(PowerEEG a) {
        this.userId = a.getUserId();
        this.lowAlpha = a.getLowAlpha();
        this.highAlpha = a.getHighAlpha();
        this.lowBeta = a.getLowBeta();
        this.highBeta = a.getHighBeta();
        this.lowGamma = a.getLowGamma();
        this.midGamma = a.getMidGamma();
        this.theta = a.getTheta();
        this.delta = a.getDelta();
        this.collectionDate = a.getCollectionDate();
    }

    public static PowerEEG[] convertToArray(List<PowerEEG> data) {
        PowerEEG[] array = new PowerEEG[data.size()];
        int i = 0;
        for (PowerEEG a : data) {
            array[i++] = new PowerEEG(a);
        }
        return array;
    }

    public static PowerEEG[] convertParcelableToPowerEEG(Parcelable[] data) {
        PowerEEG[] array = new PowerEEG[data.length];
        int i = 0;
        for (Parcelable parcel : data) {
            array[i++] = (PowerEEG) parcel;
        }
        return array;
    }
    // KEEP METHODS END

}
