package pl.mbos.bachelor_thesis.objs;

// THIS CODE IS GENERATED BY greenDAO, DO NOT EDIT. Enable "keep" sections if you want to edit. 

import org.json.JSONException;
import org.json.JSONObject;

/**
 * Entity mapped to table USER.
 */
public class User {

	public static final String USER_KEY = User.class.getCanonicalName() + ".USER_KEY";
	public static final String REASON_KEY = User.class.getCanonicalName() + ".REASON_KEY";

	private long id;
	/**
	 * Not-null value.
	 */
	private String firstName;
	/**
	 * Not-null value.
	 */
	private String lastName;

	public User() {
	}

	public User(long id) {
		this.id = id;
	}

	public User(long id, String firstName, String lastName) {
		this.id = id;
		this.firstName = firstName;
		this.lastName = lastName;
	}

	public long getId() {
		return id;
	}

	public void setId(long id) {
		this.id = id;
	}

	/**
	 * Not-null value.
	 */
	public String getFirstName() {
		return firstName;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setFirstName(String firstName) {
		this.firstName = firstName;
	}

	/**
	 * Not-null value.
	 */
	public String getLastName() {
		return lastName;
	}

	/**
	 * Not-null value; ensure this value is available before it is saved to the
	 * database.
	 */
	public void setLastName(String lastName) {
		this.lastName = lastName;
	}

	public static User parseJSON(JSONObject object) throws JSONException {
		User user = null;
		long id = object.getLong("id");
		String first = object.getString("firstName");
		String last = object.getString("lastName");
		user = new User(id, first, last);
		return user;
	}

	public String toJSON() {
		StringBuilder jsonBuilder = new StringBuilder();
		jsonBuilder.append("{ ");
		jsonBuilder.append("\"id\" : " + id + ",");
		jsonBuilder.append("\"firstName\" : \"" + firstName + "\",");
		jsonBuilder.append("\"lastName\" : \"" + lastName + "\"");
		jsonBuilder.append(" }");
		return jsonBuilder.toString();
	}
}
